name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  setup-environment:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/my-ec2-keypair.pem
          chmod 600 ~/.ssh/my-ec2-keypair.pem
      
      - name: Pull Docker Image
        run: |
          docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_KEY" > my-ec2-keypair.pem
          chmod 600 my-ec2-keypair.pem
          # Continue with your deployment commands
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        
      