name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: |
          docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: SSH into EC2 Instance and Deploy
        run: |
          ssh -i /path/to/your/private-key.pem -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip 'docker stop your-container-name || true'
          ssh -i /path/to/your/private-key.pem -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip 'docker rm your-container-name || true'
          ssh -i /path/to/your/private-key.pem -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip 'docker run -d --name your-container-name -p 80:80 ghcr.io/cbhavya09/cicd-python:${{ github.sha }}'

