name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Pull the Docker image that was built and pushed during CI
      - name: Pull Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull bhavya04/pythondeploy:${{ github.sha }}
        
      # Deploy the Docker image to your target environment (e.g., Kubernetes)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f your-deployment.yaml
