name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  setup-environment:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/my-ec2-keypair.pem
          chmod 600 ~/.ssh/my-ec2-keypair.pem
      
      - name: Pull Docker Image
        run: |
          docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}
                
      - name: SSH into EC2 Instance and Deploy
        run: |
          ssh -i "C:\Users\c.bhavya\Desktop\cicd\python-app\my-ec2-keypair.pem" -o StrictHostKeyChecking=no ec2-user@54.185.40.56 '
            docker stop samplepythoncontainer || true
            docker rm samplepythoncontainer || true
            docker run -d --name samplepythoncontainer -p 80:80 ghcr.io/cbhavya09/cicd-python:984be52eb5d51c37722144d43666aee6c949319f
          '
      
        
        
      