name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/my-ec2-keypair.pem
          chmod 600 ~/.ssh/my-ec2-keypair.pem
      
      - name: Pull Docker Image
        run: |
          docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: Run Docker Image
        run: |
          docker run -d -p 5000:5000 ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
            docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 5000:5000 ghcr.io/cbhavya09/cicd-python:${{ github.sha }}
            