name: CD

on:
  workflow_run:
    workflows: ["CI"]  # Trigger this workflow when the CI workflow completes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance's public IP or DNS
          username: ${{ secrets.EC2_USERNAME }}  # Replace with your SSH username
          key: ${{ secrets.EC2_SSH_KEY }}  # Replace with your SSH private key (stored as a secret)

      - name: Deploy Docker image to EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker stop my-app-container || true'  # Stop the previous container (if exists)
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker rm my-app-container || true'  # Remove the previous container (if exists)
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker run -d -p 80:80 --name my-app-container ghcr.io/cbhavya09/cicd-python:${{ github.sha }}'

