name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: |
          docker login ghcr.io -u cbhavya09 -p ${{ secrets.PAT_TOKEN }}
          docker pull ghcr.io/cbhavya09/cicd-python:${{ github.sha }}

      - name: SSH into EC2 Instance and Deploy
        run: |
            ssh -i C:\\Users\\c.bhavya\\Desktop\\cicd\\python app\\pytsample.pem -o StrictHostKeyChecking=no ec2-user@34.217.11.116 'docker stop samplepythoncontainer || true'
            ssh -i C:\\Users\\c.bhavya\\Desktop\\cicd\\python app\\pytsample.pem -o StrictHostKeyChecking=no ec2-user@34.217.11.116 'docker rm samplepythoncontainer || true'
            ssh -i C:\\Users\\c.bhavya\\Desktop\\cicd\\python app\\pytsample.pem -o StrictHostKeyChecking=no ec2-user@34.217.11.116 'docker run -d --name samplepythoncontainer -p 80:80 ghcr.io/cbhavya09/cicd-python:${{ github.sha }}'
        
