name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Build Docker image
        run: |
          docker build -t pythondeploy:${{ github.sha }} .
          echo "::set-output name=image_tag::pythondeploy:${{ github.sha }}"
        id: build
        continue-on-error: true

      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push pythondeploy:${{ github.sha }}
        if: steps.build.outcome == 'success'
